#
FROM node:20-alpine


WORKDIR /app
RUN apk add --no-cache \
  wireguard-tools \
  iproute2 \
  iputils \
  bash \
  curl \
  net-tools \
  && rm -rf /var/cache/apk/*

COPY package*.json ./

RUN npm install

RUN 
COPY . .

CMD ["sh", "-c", "wg-quick up wg0 && npm start"]




